global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'like-microservice_inst1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:56149']
  - job_name: 'like-microservice_inst2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:56205']
  - job_name: 'like-microservice_inst3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:56215']
  - job_name: postgres-exporter
    static_configs:
      - targets: ['host.docker.internal:9187']