server.port: 8080
spring.application.name: Api-Gateway

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8081/eureka

spring.cloud.gateway.discovery.locator.enabled: true
spring.cloud.gateway.discovery.locator.lower-case-service-id: true

management.endpoints.web.exposure.include: health,prometheus
management.metrics.export.prometheus.enabled: true
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://Like-server
          predicates:
            - Path=/test
            - Method=GET
        - id: like
          uri: lb://Like-server
          predicates:
            - Path=/like/{name}
            - Method=POST